CREATE TABLE integration_message_jobs (
  id CHAR(36) PRIMARY KEY,
  organization_id CHAR(36) NOT NULL,
  conversation_id CHAR(36) NOT NULL,
  message_id CHAR(36) NOT NULL,
  idempotency_key VARCHAR(190) NOT NULL,
  external_id VARCHAR(190) NULL,
  phone VARCHAR(32) NOT NULL,
  template_name VARCHAR(512) NOT NULL,
  language VARCHAR(20) NOT NULL,
  parameters JSON NOT NULL,
  metadata JSON NULL,
  scheduled_for DATETIME(3) NOT NULL,
  status ENUM('pending','processing','sent','failed','cancelled') NOT NULL DEFAULT 'pending',
  attempts TINYINT UNSIGNED NOT NULL DEFAULT 0,
  error_message TEXT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  processed_at DATETIME(3) NULL,
  UNIQUE KEY uq_integration_idempotency (organization_id, idempotency_key),
  KEY idx_integration_due (status, scheduled_for),
  KEY idx_integration_external (organization_id, external_id),
  CONSTRAINT fk_integration_job_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  CONSTRAINT fk_integration_job_conversation FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE,
  CONSTRAINT fk_integration_job_message FOREIGN KEY (message_id) REFERENCES messages(id) ON DELETE CASCADE
);
