CREATE TABLE campaigns (
  id CHAR(36) PRIMARY KEY,
  organization_id CHAR(36) NOT NULL,
  created_by_user_id CHAR(36) NOT NULL,
  name VARCHAR(160) NOT NULL,
  description VARCHAR(500) NULL,
  template_name VARCHAR(512) NOT NULL,
  template_language VARCHAR(20) NOT NULL,
  template_components JSON NOT NULL,
  template_preview TEXT NULL,
  delay_seconds INT UNSIGNED NOT NULL DEFAULT 5,
  scheduled_for DATETIME(3) NOT NULL,
  next_send_at DATETIME(3) NULL,
  status ENUM('draft','scheduled','running','paused','completed','cancelled') NOT NULL DEFAULT 'scheduled',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  started_at DATETIME(3) NULL,
  completed_at DATETIME(3) NULL,
  KEY idx_campaigns_org_time (organization_id, created_at),
  KEY idx_campaigns_worker (status, next_send_at),
  CONSTRAINT fk_campaigns_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  CONSTRAINT fk_campaigns_user FOREIGN KEY (created_by_user_id) REFERENCES users(id)
);

CREATE TABLE campaign_recipients (
  id CHAR(36) PRIMARY KEY,
  campaign_id CHAR(36) NOT NULL,
  organization_id CHAR(36) NOT NULL,
  contact_id CHAR(36) NULL,
  message_id CHAR(36) NULL,
  name VARCHAR(160) NULL,
  phone VARCHAR(32) NOT NULL,
  status ENUM('pending','processing','sent','delivered','read','failed','cancelled') NOT NULL DEFAULT 'pending',
  meta_message_id VARCHAR(255) NULL,
  error_message TEXT NULL,
  attempts TINYINT UNSIGNED NOT NULL DEFAULT 0,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  sent_at DATETIME(3) NULL,
  delivered_at DATETIME(3) NULL,
  read_at DATETIME(3) NULL,
  UNIQUE KEY uq_campaign_recipient (campaign_id, phone),
  KEY idx_campaign_recipient_queue (campaign_id, status, created_at),
  KEY idx_campaign_recipient_meta (meta_message_id),
  CONSTRAINT fk_campaign_recipient_campaign FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE,
  CONSTRAINT fk_campaign_recipient_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  CONSTRAINT fk_campaign_recipient_contact FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE SET NULL,
  CONSTRAINT fk_campaign_recipient_message FOREIGN KEY (message_id) REFERENCES messages(id) ON DELETE SET NULL
);
