CREATE TABLE payment_links (
  id CHAR(36) PRIMARY KEY,
  organization_id CHAR(36) NOT NULL,
  conversation_id CHAR(36) NOT NULL,
  contact_id CHAR(36) NOT NULL,
  created_by_user_id CHAR(36) NOT NULL,
  customer_name VARCHAR(160) NOT NULL,
  customer_email VARCHAR(190) NULL,
  customer_phone VARCHAR(32) NULL,
  description VARCHAR(500) NULL,
  amount DECIMAL(12,2) NOT NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'creating',
  payment_id VARCHAR(100) NULL,
  preference_id VARCHAR(255) NULL,
  payment_url TEXT NULL,
  external_reference VARCHAR(64) NOT NULL,
  error_message TEXT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  paid_at DATETIME(3) NULL,
  UNIQUE KEY uq_payment_links_reference (external_reference),
  KEY idx_payment_links_conversation (conversation_id, created_at),
  KEY idx_payment_links_payment (payment_id),
  CONSTRAINT fk_payment_links_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  CONSTRAINT fk_payment_links_conversation FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE,
  CONSTRAINT fk_payment_links_contact FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE CASCADE,
  CONSTRAINT fk_payment_links_user FOREIGN KEY (created_by_user_id) REFERENCES users(id)
);
